# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /data/data/com.termux/files/usr/bin/sh

# The CMake executable.
CMAKE_COMMAND = /data/data/com.termux/files/usr/bin/cmake

# The command to remove a file.
RM = /data/data/com.termux/files/usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/data/com.termux/files/home/tuyotuyo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/data/com.termux/files/home/tuyotuyo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/data/data/com.termux/files/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/data/data/com.termux/files/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/tuyotuyo/CMakeFiles /data/data/com.termux/files/home/tuyotuyo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/tuyotuyo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tuyotuyo.out

# Build rule for target.
tuyotuyo.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tuyotuyo.out
.PHONY : tuyotuyo.out

# fast build rule for target.
tuyotuyo.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/build
.PHONY : tuyotuyo.out/fast

#=============================================================================
# Target rules for targets named tuyotuyo

# Build rule for target.
tuyotuyo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tuyotuyo
.PHONY : tuyotuyo

# fast build rule for target.
tuyotuyo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/build
.PHONY : tuyotuyo/fast

tuyotuyo/AI.o: tuyotuyo/AI.cpp.o
.PHONY : tuyotuyo/AI.o

# target to build an object file
tuyotuyo/AI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/AI.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/AI.cpp.o
.PHONY : tuyotuyo/AI.cpp.o

tuyotuyo/AI.i: tuyotuyo/AI.cpp.i
.PHONY : tuyotuyo/AI.i

# target to preprocess a source file
tuyotuyo/AI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/AI.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/AI.cpp.i
.PHONY : tuyotuyo/AI.cpp.i

tuyotuyo/AI.s: tuyotuyo/AI.cpp.s
.PHONY : tuyotuyo/AI.s

# target to generate assembly for a file
tuyotuyo/AI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/AI.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/AI.cpp.s
.PHONY : tuyotuyo/AI.cpp.s

tuyotuyo/CrossFunc.o: tuyotuyo/CrossFunc.cpp.o
.PHONY : tuyotuyo/CrossFunc.o

# target to build an object file
tuyotuyo/CrossFunc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/CrossFunc.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/CrossFunc.cpp.o
.PHONY : tuyotuyo/CrossFunc.cpp.o

tuyotuyo/CrossFunc.i: tuyotuyo/CrossFunc.cpp.i
.PHONY : tuyotuyo/CrossFunc.i

# target to preprocess a source file
tuyotuyo/CrossFunc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/CrossFunc.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/CrossFunc.cpp.i
.PHONY : tuyotuyo/CrossFunc.cpp.i

tuyotuyo/CrossFunc.s: tuyotuyo/CrossFunc.cpp.s
.PHONY : tuyotuyo/CrossFunc.s

# target to generate assembly for a file
tuyotuyo/CrossFunc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/CrossFunc.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/CrossFunc.cpp.s
.PHONY : tuyotuyo/CrossFunc.cpp.s

tuyotuyo/Detected.o: tuyotuyo/Detected.cpp.o
.PHONY : tuyotuyo/Detected.o

# target to build an object file
tuyotuyo/Detected.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/Detected.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/Detected.cpp.o
.PHONY : tuyotuyo/Detected.cpp.o

tuyotuyo/Detected.i: tuyotuyo/Detected.cpp.i
.PHONY : tuyotuyo/Detected.i

# target to preprocess a source file
tuyotuyo/Detected.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/Detected.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/Detected.cpp.i
.PHONY : tuyotuyo/Detected.cpp.i

tuyotuyo/Detected.s: tuyotuyo/Detected.cpp.s
.PHONY : tuyotuyo/Detected.s

# target to generate assembly for a file
tuyotuyo/Detected.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/Detected.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/Detected.cpp.s
.PHONY : tuyotuyo/Detected.cpp.s

tuyotuyo/Detector.o: tuyotuyo/Detector.cpp.o
.PHONY : tuyotuyo/Detector.o

# target to build an object file
tuyotuyo/Detector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/Detector.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/Detector.cpp.o
.PHONY : tuyotuyo/Detector.cpp.o

tuyotuyo/Detector.i: tuyotuyo/Detector.cpp.i
.PHONY : tuyotuyo/Detector.i

# target to preprocess a source file
tuyotuyo/Detector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/Detector.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/Detector.cpp.i
.PHONY : tuyotuyo/Detector.cpp.i

tuyotuyo/Detector.s: tuyotuyo/Detector.cpp.s
.PHONY : tuyotuyo/Detector.s

# target to generate assembly for a file
tuyotuyo/Detector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/Detector.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/Detector.cpp.s
.PHONY : tuyotuyo/Detector.cpp.s

tuyotuyo/DlAI.o: tuyotuyo/DlAI.cpp.o
.PHONY : tuyotuyo/DlAI.o

# target to build an object file
tuyotuyo/DlAI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/DlAI.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/DlAI.cpp.o
.PHONY : tuyotuyo/DlAI.cpp.o

tuyotuyo/DlAI.i: tuyotuyo/DlAI.cpp.i
.PHONY : tuyotuyo/DlAI.i

# target to preprocess a source file
tuyotuyo/DlAI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/DlAI.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/DlAI.cpp.i
.PHONY : tuyotuyo/DlAI.cpp.i

tuyotuyo/DlAI.s: tuyotuyo/DlAI.cpp.s
.PHONY : tuyotuyo/DlAI.s

# target to generate assembly for a file
tuyotuyo/DlAI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/DlAI.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/DlAI.cpp.s
.PHONY : tuyotuyo/DlAI.cpp.s

tuyotuyo/Duel.o: tuyotuyo/Duel.cpp.o
.PHONY : tuyotuyo/Duel.o

# target to build an object file
tuyotuyo/Duel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/Duel.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/Duel.cpp.o
.PHONY : tuyotuyo/Duel.cpp.o

tuyotuyo/Duel.i: tuyotuyo/Duel.cpp.i
.PHONY : tuyotuyo/Duel.i

# target to preprocess a source file
tuyotuyo/Duel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/Duel.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/Duel.cpp.i
.PHONY : tuyotuyo/Duel.cpp.i

tuyotuyo/Duel.s: tuyotuyo/Duel.cpp.s
.PHONY : tuyotuyo/Duel.s

# target to generate assembly for a file
tuyotuyo/Duel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/Duel.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/Duel.cpp.s
.PHONY : tuyotuyo/Duel.cpp.s

tuyotuyo/DuelAIAI.o: tuyotuyo/DuelAIAI.cpp.o
.PHONY : tuyotuyo/DuelAIAI.o

# target to build an object file
tuyotuyo/DuelAIAI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/DuelAIAI.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/DuelAIAI.cpp.o
.PHONY : tuyotuyo/DuelAIAI.cpp.o

tuyotuyo/DuelAIAI.i: tuyotuyo/DuelAIAI.cpp.i
.PHONY : tuyotuyo/DuelAIAI.i

# target to preprocess a source file
tuyotuyo/DuelAIAI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/DuelAIAI.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/DuelAIAI.cpp.i
.PHONY : tuyotuyo/DuelAIAI.cpp.i

tuyotuyo/DuelAIAI.s: tuyotuyo/DuelAIAI.cpp.s
.PHONY : tuyotuyo/DuelAIAI.s

# target to generate assembly for a file
tuyotuyo/DuelAIAI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/DuelAIAI.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/DuelAIAI.cpp.s
.PHONY : tuyotuyo/DuelAIAI.cpp.s

tuyotuyo/DuelOptimizer.o: tuyotuyo/DuelOptimizer.cpp.o
.PHONY : tuyotuyo/DuelOptimizer.o

# target to build an object file
tuyotuyo/DuelOptimizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/DuelOptimizer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/DuelOptimizer.cpp.o
.PHONY : tuyotuyo/DuelOptimizer.cpp.o

tuyotuyo/DuelOptimizer.i: tuyotuyo/DuelOptimizer.cpp.i
.PHONY : tuyotuyo/DuelOptimizer.i

# target to preprocess a source file
tuyotuyo/DuelOptimizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/DuelOptimizer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/DuelOptimizer.cpp.i
.PHONY : tuyotuyo/DuelOptimizer.cpp.i

tuyotuyo/DuelOptimizer.s: tuyotuyo/DuelOptimizer.cpp.s
.PHONY : tuyotuyo/DuelOptimizer.s

# target to generate assembly for a file
tuyotuyo/DuelOptimizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/DuelOptimizer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/DuelOptimizer.cpp.s
.PHONY : tuyotuyo/DuelOptimizer.cpp.s

tuyotuyo/DuelPy.o: tuyotuyo/DuelPy.cpp.o
.PHONY : tuyotuyo/DuelPy.o

# target to build an object file
tuyotuyo/DuelPy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/DuelPy.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/DuelPy.cpp.o
.PHONY : tuyotuyo/DuelPy.cpp.o

tuyotuyo/DuelPy.i: tuyotuyo/DuelPy.cpp.i
.PHONY : tuyotuyo/DuelPy.i

# target to preprocess a source file
tuyotuyo/DuelPy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/DuelPy.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/DuelPy.cpp.i
.PHONY : tuyotuyo/DuelPy.cpp.i

tuyotuyo/DuelPy.s: tuyotuyo/DuelPy.cpp.s
.PHONY : tuyotuyo/DuelPy.s

# target to generate assembly for a file
tuyotuyo/DuelPy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/DuelPy.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/DuelPy.cpp.s
.PHONY : tuyotuyo/DuelPy.cpp.s

tuyotuyo/DuelToko.o: tuyotuyo/DuelToko.cpp.o
.PHONY : tuyotuyo/DuelToko.o

# target to build an object file
tuyotuyo/DuelToko.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/DuelToko.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/DuelToko.cpp.o
.PHONY : tuyotuyo/DuelToko.cpp.o

tuyotuyo/DuelToko.i: tuyotuyo/DuelToko.cpp.i
.PHONY : tuyotuyo/DuelToko.i

# target to preprocess a source file
tuyotuyo/DuelToko.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/DuelToko.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/DuelToko.cpp.i
.PHONY : tuyotuyo/DuelToko.cpp.i

tuyotuyo/DuelToko.s: tuyotuyo/DuelToko.cpp.s
.PHONY : tuyotuyo/DuelToko.s

# target to generate assembly for a file
tuyotuyo/DuelToko.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/DuelToko.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/DuelToko.cpp.s
.PHONY : tuyotuyo/DuelToko.cpp.s

tuyotuyo/FormAI.o: tuyotuyo/FormAI.cpp.o
.PHONY : tuyotuyo/FormAI.o

# target to build an object file
tuyotuyo/FormAI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/FormAI.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/FormAI.cpp.o
.PHONY : tuyotuyo/FormAI.cpp.o

tuyotuyo/FormAI.i: tuyotuyo/FormAI.cpp.i
.PHONY : tuyotuyo/FormAI.i

# target to preprocess a source file
tuyotuyo/FormAI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/FormAI.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/FormAI.cpp.i
.PHONY : tuyotuyo/FormAI.cpp.i

tuyotuyo/FormAI.s: tuyotuyo/FormAI.cpp.s
.PHONY : tuyotuyo/FormAI.s

# target to generate assembly for a file
tuyotuyo/FormAI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/FormAI.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/FormAI.cpp.s
.PHONY : tuyotuyo/FormAI.cpp.s

tuyotuyo/GameInfo.o: tuyotuyo/GameInfo.cpp.o
.PHONY : tuyotuyo/GameInfo.o

# target to build an object file
tuyotuyo/GameInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/GameInfo.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/GameInfo.cpp.o
.PHONY : tuyotuyo/GameInfo.cpp.o

tuyotuyo/GameInfo.i: tuyotuyo/GameInfo.cpp.i
.PHONY : tuyotuyo/GameInfo.i

# target to preprocess a source file
tuyotuyo/GameInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/GameInfo.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/GameInfo.cpp.i
.PHONY : tuyotuyo/GameInfo.cpp.i

tuyotuyo/GameInfo.s: tuyotuyo/GameInfo.cpp.s
.PHONY : tuyotuyo/GameInfo.s

# target to generate assembly for a file
tuyotuyo/GameInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/GameInfo.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/GameInfo.cpp.s
.PHONY : tuyotuyo/GameInfo.cpp.s

tuyotuyo/MSVAI.o: tuyotuyo/MSVAI.cpp.o
.PHONY : tuyotuyo/MSVAI.o

# target to build an object file
tuyotuyo/MSVAI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/MSVAI.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/MSVAI.cpp.o
.PHONY : tuyotuyo/MSVAI.cpp.o

tuyotuyo/MSVAI.i: tuyotuyo/MSVAI.cpp.i
.PHONY : tuyotuyo/MSVAI.i

# target to preprocess a source file
tuyotuyo/MSVAI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/MSVAI.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/MSVAI.cpp.i
.PHONY : tuyotuyo/MSVAI.cpp.i

tuyotuyo/MSVAI.s: tuyotuyo/MSVAI.cpp.s
.PHONY : tuyotuyo/MSVAI.s

# target to generate assembly for a file
tuyotuyo/MSVAI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/MSVAI.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/MSVAI.cpp.s
.PHONY : tuyotuyo/MSVAI.cpp.s

tuyotuyo/NeuralNet.o: tuyotuyo/NeuralNet.cpp.o
.PHONY : tuyotuyo/NeuralNet.o

# target to build an object file
tuyotuyo/NeuralNet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/NeuralNet.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/NeuralNet.cpp.o
.PHONY : tuyotuyo/NeuralNet.cpp.o

tuyotuyo/NeuralNet.i: tuyotuyo/NeuralNet.cpp.i
.PHONY : tuyotuyo/NeuralNet.i

# target to preprocess a source file
tuyotuyo/NeuralNet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/NeuralNet.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/NeuralNet.cpp.i
.PHONY : tuyotuyo/NeuralNet.cpp.i

tuyotuyo/NeuralNet.s: tuyotuyo/NeuralNet.cpp.s
.PHONY : tuyotuyo/NeuralNet.s

# target to generate assembly for a file
tuyotuyo/NeuralNet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/NeuralNet.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/NeuralNet.cpp.s
.PHONY : tuyotuyo/NeuralNet.cpp.s

tuyotuyo/Plan.o: tuyotuyo/Plan.cpp.o
.PHONY : tuyotuyo/Plan.o

# target to build an object file
tuyotuyo/Plan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/Plan.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/Plan.cpp.o
.PHONY : tuyotuyo/Plan.cpp.o

tuyotuyo/Plan.i: tuyotuyo/Plan.cpp.i
.PHONY : tuyotuyo/Plan.i

# target to preprocess a source file
tuyotuyo/Plan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/Plan.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/Plan.cpp.i
.PHONY : tuyotuyo/Plan.cpp.i

tuyotuyo/Plan.s: tuyotuyo/Plan.cpp.s
.PHONY : tuyotuyo/Plan.s

# target to generate assembly for a file
tuyotuyo/Plan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/Plan.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/Plan.cpp.s
.PHONY : tuyotuyo/Plan.cpp.s

tuyotuyo/PlanTest.o: tuyotuyo/PlanTest.cpp.o
.PHONY : tuyotuyo/PlanTest.o

# target to build an object file
tuyotuyo/PlanTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/PlanTest.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/PlanTest.cpp.o
.PHONY : tuyotuyo/PlanTest.cpp.o

tuyotuyo/PlanTest.i: tuyotuyo/PlanTest.cpp.i
.PHONY : tuyotuyo/PlanTest.i

# target to preprocess a source file
tuyotuyo/PlanTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/PlanTest.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/PlanTest.cpp.i
.PHONY : tuyotuyo/PlanTest.cpp.i

tuyotuyo/PlanTest.s: tuyotuyo/PlanTest.cpp.s
.PHONY : tuyotuyo/PlanTest.s

# target to generate assembly for a file
tuyotuyo/PlanTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/PlanTest.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/PlanTest.cpp.s
.PHONY : tuyotuyo/PlanTest.cpp.s

tuyotuyo/PuyoTsumo.o: tuyotuyo/PuyoTsumo.cpp.o
.PHONY : tuyotuyo/PuyoTsumo.o

# target to build an object file
tuyotuyo/PuyoTsumo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/PuyoTsumo.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/PuyoTsumo.cpp.o
.PHONY : tuyotuyo/PuyoTsumo.cpp.o

tuyotuyo/PuyoTsumo.i: tuyotuyo/PuyoTsumo.cpp.i
.PHONY : tuyotuyo/PuyoTsumo.i

# target to preprocess a source file
tuyotuyo/PuyoTsumo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/PuyoTsumo.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/PuyoTsumo.cpp.i
.PHONY : tuyotuyo/PuyoTsumo.cpp.i

tuyotuyo/PuyoTsumo.s: tuyotuyo/PuyoTsumo.cpp.s
.PHONY : tuyotuyo/PuyoTsumo.s

# target to generate assembly for a file
tuyotuyo/PuyoTsumo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/PuyoTsumo.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/PuyoTsumo.cpp.s
.PHONY : tuyotuyo/PuyoTsumo.cpp.s

tuyotuyo/SaveAI.o: tuyotuyo/SaveAI.cpp.o
.PHONY : tuyotuyo/SaveAI.o

# target to build an object file
tuyotuyo/SaveAI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/SaveAI.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/SaveAI.cpp.o
.PHONY : tuyotuyo/SaveAI.cpp.o

tuyotuyo/SaveAI.i: tuyotuyo/SaveAI.cpp.i
.PHONY : tuyotuyo/SaveAI.i

# target to preprocess a source file
tuyotuyo/SaveAI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/SaveAI.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/SaveAI.cpp.i
.PHONY : tuyotuyo/SaveAI.cpp.i

tuyotuyo/SaveAI.s: tuyotuyo/SaveAI.cpp.s
.PHONY : tuyotuyo/SaveAI.s

# target to generate assembly for a file
tuyotuyo/SaveAI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/SaveAI.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/SaveAI.cpp.s
.PHONY : tuyotuyo/SaveAI.cpp.s

tuyotuyo/Simulator.o: tuyotuyo/Simulator.cpp.o
.PHONY : tuyotuyo/Simulator.o

# target to build an object file
tuyotuyo/Simulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/Simulator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/Simulator.cpp.o
.PHONY : tuyotuyo/Simulator.cpp.o

tuyotuyo/Simulator.i: tuyotuyo/Simulator.cpp.i
.PHONY : tuyotuyo/Simulator.i

# target to preprocess a source file
tuyotuyo/Simulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/Simulator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/Simulator.cpp.i
.PHONY : tuyotuyo/Simulator.cpp.i

tuyotuyo/Simulator.s: tuyotuyo/Simulator.cpp.s
.PHONY : tuyotuyo/Simulator.s

# target to generate assembly for a file
tuyotuyo/Simulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/Simulator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/Simulator.cpp.s
.PHONY : tuyotuyo/Simulator.cpp.s

tuyotuyo/Tuyotuyo.o: tuyotuyo/Tuyotuyo.cpp.o
.PHONY : tuyotuyo/Tuyotuyo.o

# target to build an object file
tuyotuyo/Tuyotuyo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/Tuyotuyo.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/Tuyotuyo.cpp.o
.PHONY : tuyotuyo/Tuyotuyo.cpp.o

tuyotuyo/Tuyotuyo.i: tuyotuyo/Tuyotuyo.cpp.i
.PHONY : tuyotuyo/Tuyotuyo.i

# target to preprocess a source file
tuyotuyo/Tuyotuyo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/Tuyotuyo.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/Tuyotuyo.cpp.i
.PHONY : tuyotuyo/Tuyotuyo.cpp.i

tuyotuyo/Tuyotuyo.s: tuyotuyo/Tuyotuyo.cpp.s
.PHONY : tuyotuyo/Tuyotuyo.s

# target to generate assembly for a file
tuyotuyo/Tuyotuyo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.out.dir/build.make CMakeFiles/tuyotuyo.out.dir/tuyotuyo/Tuyotuyo.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tuyotuyo.dir/build.make CMakeFiles/tuyotuyo.dir/tuyotuyo/Tuyotuyo.cpp.s
.PHONY : tuyotuyo/Tuyotuyo.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tuyotuyo"
	@echo "... tuyotuyo.out"
	@echo "... tuyotuyo/AI.o"
	@echo "... tuyotuyo/AI.i"
	@echo "... tuyotuyo/AI.s"
	@echo "... tuyotuyo/CrossFunc.o"
	@echo "... tuyotuyo/CrossFunc.i"
	@echo "... tuyotuyo/CrossFunc.s"
	@echo "... tuyotuyo/Detected.o"
	@echo "... tuyotuyo/Detected.i"
	@echo "... tuyotuyo/Detected.s"
	@echo "... tuyotuyo/Detector.o"
	@echo "... tuyotuyo/Detector.i"
	@echo "... tuyotuyo/Detector.s"
	@echo "... tuyotuyo/DlAI.o"
	@echo "... tuyotuyo/DlAI.i"
	@echo "... tuyotuyo/DlAI.s"
	@echo "... tuyotuyo/Duel.o"
	@echo "... tuyotuyo/Duel.i"
	@echo "... tuyotuyo/Duel.s"
	@echo "... tuyotuyo/DuelAIAI.o"
	@echo "... tuyotuyo/DuelAIAI.i"
	@echo "... tuyotuyo/DuelAIAI.s"
	@echo "... tuyotuyo/DuelOptimizer.o"
	@echo "... tuyotuyo/DuelOptimizer.i"
	@echo "... tuyotuyo/DuelOptimizer.s"
	@echo "... tuyotuyo/DuelPy.o"
	@echo "... tuyotuyo/DuelPy.i"
	@echo "... tuyotuyo/DuelPy.s"
	@echo "... tuyotuyo/DuelToko.o"
	@echo "... tuyotuyo/DuelToko.i"
	@echo "... tuyotuyo/DuelToko.s"
	@echo "... tuyotuyo/FormAI.o"
	@echo "... tuyotuyo/FormAI.i"
	@echo "... tuyotuyo/FormAI.s"
	@echo "... tuyotuyo/GameInfo.o"
	@echo "... tuyotuyo/GameInfo.i"
	@echo "... tuyotuyo/GameInfo.s"
	@echo "... tuyotuyo/MSVAI.o"
	@echo "... tuyotuyo/MSVAI.i"
	@echo "... tuyotuyo/MSVAI.s"
	@echo "... tuyotuyo/NeuralNet.o"
	@echo "... tuyotuyo/NeuralNet.i"
	@echo "... tuyotuyo/NeuralNet.s"
	@echo "... tuyotuyo/Plan.o"
	@echo "... tuyotuyo/Plan.i"
	@echo "... tuyotuyo/Plan.s"
	@echo "... tuyotuyo/PlanTest.o"
	@echo "... tuyotuyo/PlanTest.i"
	@echo "... tuyotuyo/PlanTest.s"
	@echo "... tuyotuyo/PuyoTsumo.o"
	@echo "... tuyotuyo/PuyoTsumo.i"
	@echo "... tuyotuyo/PuyoTsumo.s"
	@echo "... tuyotuyo/SaveAI.o"
	@echo "... tuyotuyo/SaveAI.i"
	@echo "... tuyotuyo/SaveAI.s"
	@echo "... tuyotuyo/Simulator.o"
	@echo "... tuyotuyo/Simulator.i"
	@echo "... tuyotuyo/Simulator.s"
	@echo "... tuyotuyo/Tuyotuyo.o"
	@echo "... tuyotuyo/Tuyotuyo.i"
	@echo "... tuyotuyo/Tuyotuyo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

